### ISSUE TITLE
Just downloaded from PyPI and cannot find main

### ISSUE THREAD

**Issue by D3f0** [JdeH/Numscrypt#1]
On OS X 10.10.4 with Homebrew Python (same outcome in or out of venv)
```shell
(transcrypt) ~ » transcrypt
Traceback (most recent call last):
  File "/Users/nahuel/.virtualenvs/transcrypt/bin/transcrypt", line 7, in <module>
    from transcrypt.__main__ import main
ImportError: No module named transcrypt.__main__
```
PS: I've heard about the project on the podcast and it really sounded like something I could use in my projects.

**Comment by JdeH** [comment]
Hi

To investigate this apparent installation problem, I did some experimenting on OS X Mavericks 10.9 and got both Transcrypt and Numscrypt to work as follows:

- Install miniconda for OSX and Python3.5 from http://conda.pydata.org/miniconda.html
- To also be able to test Numscrypt against Numpy, from a terminal type:

conda install numpy

Then close and reopen your terminal. Numpy will now be available.

From that terminal type:

python3.5 -m pip install numscrypt

This will install the latest versions of Numscrypt and Transcrypt into the conda installation.
After that everything just works with me, for both Numscrypt and Transcrypt.

As an alternative, you can bypass automatic installation altogether, using the manual installation procedure described at:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/installation_use.html#installation

Note that in this case Transcrypt is started by typing run_transcrypt rather than transcrypt, to make the disctinction if both installations are present.

The ImportError you get isn't generated by any code from Transcrypt but by a piece of code that's automatically generated by your installation program.

Once everyting is installed properly, you can view the options by typing transcrypt -h (or if you installed manually: run_transcrypt -h.

Furthermore I tried to run the autotests and demos in Safari. Not all of them will run, since Safari JS  misses some ES 5 features. So I downloaded Chrome into OSX, and it all worked.

The anaconda / miniconda installation is a very unproblematic one. In fact even on Linux there's no regular way to e.g. install Numpy into Python3.5 at all, but via miniconda it's a snap.

Although I couldn't reproduce your problem I hope these two alternative procedures help you out.

**Comment by D3f0** [comment]
@JdeH Thank you for the quick response. It seems that having both Python2 and 3 messed things up in my machine.
I overcome the issue by explicitly defining to virtualenvwrappers' `mkvirtualenv` which python executable I wanted to use as follows:
```shell
mkvirtualenv -p $(which python3.5 ) transcrypt
```
Then installed transcrypt and worked like a charm 🎉
I should have posted this in Transcrypt repo rather than Numscrypt.

Sorry for PBCAKing

**Comment by D3f0** [comment]
Maybe if a `sys.version` check could show some error about unsupported python version.

**Comment by JdeH** [comment]
Good idea, I'll add that in the next version.
And glad you got things to work.
